functional:
  T: 1.0
  n-weights: 2
  w-hidden-sizes: [30, 30]
  f-ex-hidden-sizes: [30, 30]
  load-params: mlcdft_params.dat

data:
  filenames: ../data-T1-R0.5/*.h5
  train-fraction: 0.8
  batch-size: 10

train:
  epochs: 3000
  learning-rate: 1.0E-5
  save-params: mlcdft_params.dat
