functional:
  load-file: params-gauss.dat
  layers:
  - n-weights: [6, 4]
    n-outputs: 1
    hidden-sizes: [30, 30, 30]
    activation: gelu
    use-local: True
    use-gradient: True
    weight-functions: {type: gaussian, sigma_max: 5.0, degree: 1}

data:
  filenames: random_data/*.h5
  train-fraction: 0.8

train:
  loss-curve: loss-gauss.dat
  save-file: params-gauss.dat
  save-interval: 30
  epochs: 1000
  batch-size: 400
  energy-loss-scale: 1.0
  method: Adam
  lr: 1.0E-3
  weight-decay: 1.0E-3
