functional:
  load-file: params.dat
  layers:
  - n-weights: [3, 2]
    n-outputs: 5
    hidden-sizes: [30, 30]
    activation: gelu
    basis: {type: cspline, r_max: 2.0, n_basis: 10, use_local: True, use_gradient: True}
  - n-weights: [3, 2]
    n-outputs: 5
    hidden-sizes: [30, 30]
    activation: gelu
    basis: {type: cspline, r_max: 4.0, n_basis: 10, use_local: True}
  - n-weights: [3, 2]
    n-outputs: 1
    hidden-sizes: [30, 30]
    activation: gelu
    basis: {type: cspline, r_max: 8.0, n_basis: 10, use_local: True}

data:
  filenames: random_data/*.h5
  train-fraction: 0.8

train:
  loss-curve: loss.dat
  save-file: params.dat
  save-interval: 30
  epochs: 3000
  batch-size: 400
  method: Adam
  lr: 1.0E-3
  weight-decay: 1.0E-3
