functional:
  load-file: params.dat
  n-sites: 2
  layers:
  - n-weights: [3, 2]
    n-outputs: 2
    hidden-sizes: [30, 30]
    weight-functions: {type: cspline, r-max: 2.0, n-basis: 10}

data:
  filenames: ../random_data/*.h5
  train-fraction: 0.8

train:
  loss-curve: loss.dat
  save-file: params.dat
  save-interval: 30
  epochs: 1000
  batch-size: 400
  energy-loss-scale: 1.0
  method: Adam
  lr: 1.0E-3
  weight-decay: 1.0E-3
  foreach: no  # Temporary for a bug in Adam in PyTorch 2.1
