functional:
  n-weights: 2
  w-hidden-sizes: [30, 30, 30]
  f-ex-hidden-sizes: [30, 30, 30]
  load-file: params.dat

data:
  filenames: random_data/*.h5
  train-fraction: 0.8

train:
  loss-curve: loss.dat
  save-file: params.dat
  save-interval: 30
  epochs: 3000
  batch-size: 10
  method: Adam
  lr: 1.0E-3
  weight-decay: 0.01
