functional:
  load-file: params.dat
  attr-names: [T]  # Train with temperature dependence
  layers:
  - n-out: [5, 0]
    weight-functions: {type: gaussian, sigma-max: 20.0, degree: 1}
  readout: [100, 100, 100]
  wda: yes

data:
  filenames: ../random_data/*.h5
  train-fraction: 0.8

train:
  loss-curve: loss.dat
  save-file: params.dat
  save-interval: 20
  epochs: 1000
  batch-size: 400
  energy-loss-scale: 1.0
  method: Adam
  lr: 1.0E-3
  weight-decay: 1.0E-3
  foreach: no  # Torch 2.1 bug in Adam
